#!/system/bin/sh
#
# screenstate_scaling - switch CPU frequency governor on screen state change
# originally by florian.schaefer@gmail.com (FloHimself)
#   Modifications Copyright 2010
#   Copying and distribution of this file, with or without modification,
#   are permitted in any medium without royalty provided the copyright
#   notice and this notice are preserved.


AWAKE_GOVERNOR="interactive"
AWAKE_GOVERNOR_FREQENCY_MAX="998400"
AWAKE_GOVERNOR_FREQENCY_MIN="245000"

SLEEP_GOVERNOR="interactive"
# irrelevant max for powersave
SLEEP_GOVERNOR_FREQENCY_MAX="245000"
SLEEP_GOVERNOR_FREQENCY_MIN="245000"

SETCPU="com.mhuang.overclocking"

log -p i -t screenstate_scaling "*** screenstate_scaling script up and running"

(while [ 1 ]
do
    AWAKE=`cat /sys/power/wait_for_fb_wake`
    if [ $AWAKE = "awake" ] && [ ! "`pidof $SETCPU`" ]; then
        echo $AWAKE_GOVERNOR_FREQENCY_MIN > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
        echo $AWAKE_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
        echo $AWAKE_GOVERNOR_FREQENCY_MAX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    fi
        log -p i -t screenstate_scaling "***  awake   ***: switching CPU frequency governor to -> $AWAKE_GOVERNOR"
        AWAKE=
    SLEEPING=`cat /sys/power/wait_for_fb_sleep`
    if [ $SLEEPING = "sleeping" ] && [ ! "`pidof $SETCPU`" ]; then
        echo $SLEEP_GOVERNOR_FREQENCY_MIN > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
        echo $SLEEP_GOVERNOR_FREQENCY_MAX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
        echo $SLEEP_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
        log -p i -t screenstate_scaling "*** sleeping ***: switching CPU frequency governor to -> $SLEEP_GOVERNOR"
        SLEEPING=
    fi    
done &)

